import type {
  AdminOrder,
  AdminCustomer,
  AdminProduct,
  AdminAuction,
  DashboardStats,
} from '@/types/backoffice'

function hoursFromNow(hours: number): string {
  return new Date(Date.now() + hours * 3600_000).toISOString()
}

function img(seed: string, size = 300): string {
  return `https://picsum.photos/seed/${seed}/${size}/${size}`
}

export const MOCK_STATS: DashboardStats = {
  pendingOrders: 5,
  processingOrders: 8,
  shippedOrders: 12,
  completedOrders: 143,
  totalRevenueTHB: 487_520,
  totalCustomers: 89,
}

export const MOCK_ORDERS: AdminOrder[] = [
  {
    id: 'order-1',
    orderNumber: 'KK-2026-00001',
    customerName: 'Somchai K.',
    customerEmail: 'somchai@example.com',
    status: 'COMPLETED',
    totalJPY: 15000,
    totalTHB: 3600,
    itemCount: 2,
    createdAt: '2026-03-01T09:00:00Z',
  },
  {
    id: 'order-2',
    orderNumber: 'KK-2026-00002',
    customerName: 'Nattaya P.',
    customerEmail: 'nattaya@example.com',
    status: 'SHIPPED_TO_TH',
    totalJPY: 8000,
    totalTHB: 1920,
    itemCount: 1,
    createdAt: '2026-03-03T12:00:00Z',
  },
  {
    id: 'order-3',
    orderNumber: 'KK-2026-00003',
    customerName: 'Aran W.',
    customerEmail: 'aran@example.com',
    status: 'PENDING_PAYMENT',
    totalJPY: 3500,
    totalTHB: 840,
    itemCount: 1,
    createdAt: '2026-03-06T08:00:00Z',
  },
  {
    id: 'order-4',
    orderNumber: 'KK-2026-00004',
    customerName: 'Somchai K.',
    customerEmail: 'somchai@example.com',
    status: 'PROCESSING',
    totalJPY: 12500,
    totalTHB: 3000,
    itemCount: 1,
    createdAt: '2026-03-05T15:00:00Z',
  },
  {
    id: 'order-5',
    orderNumber: 'KK-2026-00005',
    customerName: 'Pimsiri L.',
    customerEmail: 'pimsiri@example.com',
    status: 'CANCELLED',
    totalJPY: 5000,
    totalTHB: 1200,
    itemCount: 1,
    createdAt: '2026-02-27T10:00:00Z',
  },
  {
    id: 'order-6',
    orderNumber: 'KK-2026-00006',
    customerName: 'Wanida T.',
    customerEmail: 'wanida@example.com',
    status: 'PENDING_PAYMENT',
    totalJPY: 22000,
    totalTHB: 5280,
    itemCount: 3,
    createdAt: '2026-03-06T10:30:00Z',
  },
  {
    id: 'order-7',
    orderNumber: 'KK-2026-00007',
    customerName: 'Thanaporn S.',
    customerEmail: 'thanaporn@example.com',
    status: 'PROCESSING',
    totalJPY: 9800,
    totalTHB: 2352,
    itemCount: 2,
    createdAt: '2026-03-05T18:00:00Z',
  },
  {
    id: 'order-8',
    orderNumber: 'KK-2026-00008',
    customerName: 'Nattaya P.',
    customerEmail: 'nattaya@example.com',
    status: 'COMPLETED',
    totalJPY: 4200,
    totalTHB: 1008,
    itemCount: 1,
    createdAt: '2026-02-20T14:00:00Z',
  },
]

export const MOCK_CUSTOMERS: AdminCustomer[] = [
  {
    id: 'cust-1',
    name: 'Somchai Kasem',
    email: 'somchai@example.com',
    phone: '08-1111-2222',
    role: 'customer',
    isEmailVerified: true,
    orderCount: 5,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'Nattaya Promma',
    email: 'nattaya@example.com',
    phone: '08-3333-4444',
    role: 'customer',
    isEmailVerified: true,
    orderCount: 3,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'Aran Wongchai',
    email: 'aran@example.com',
    phone: '08-5555-6666',
    role: 'customer',
    isEmailVerified: false,
    orderCount: 1,
    createdAt: '2026-02-10T12:00:00Z',
  },
  {
    id: 'cust-4',
    name: 'Pimsiri Laothong',
    email: 'pimsiri@example.com',
    phone: null,
    role: 'customer',
    isEmailVerified: true,
    orderCount: 2,
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'cust-5',
    name: 'Wanida Thongprasert',
    email: 'wanida@example.com',
    phone: '08-7777-8888',
    role: 'customer',
    isEmailVerified: true,
    orderCount: 7,
    createdAt: '2025-12-05T14:00:00Z',
  },
  {
    id: 'cust-6',
    name: 'Thanaporn Srisuk',
    email: 'thanaporn@example.com',
    phone: '08-9999-0000',
    role: 'customer',
    isEmailVerified: false,
    orderCount: 0,
    createdAt: '2026-03-01T16:00:00Z',
  },
  {
    id: 'admin-1',
    name: 'Admin Sakura',
    email: 'admin@sakura.com',
    phone: '08-0000-0000',
    role: 'admin',
    isEmailVerified: true,
    orderCount: 0,
    createdAt: '2025-11-01T00:00:00Z',
  },
]

export const MOCK_PRODUCTS: AdminProduct[] = [
  {
    id: 'prod-1',
    name: 'D-UP パーフェクトエクステンションマスカラ ブラック',
    price: 650,
    imageUrl: img('mascara-black'),
    condition: 'Brand New',
    isAuction: true,
    status: 'active',
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Nintendo Switch OLED ホワイト 本体 新品未使用',
    price: 38000,
    imageUrl: img('nintendo-switch'),
    condition: 'Brand New',
    isAuction: true,
    status: 'active',
    createdAt: '2026-02-20T08:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'ポケモンカード 151 BOX シュリンク付き',
    price: 12500,
    imageUrl: img('pokemon-cards'),
    condition: 'Brand New',
    isAuction: true,
    status: 'active',
    createdAt: '2026-02-22T14:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'D-UP ワンダーアイリッドテープ Extra',
    price: 999,
    imageUrl: img('eyelid-tape'),
    condition: 'Brand New',
    isAuction: false,
    status: 'active',
    createdAt: '2026-02-25T09:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Shiseido Ultimune Serum 50ml',
    price: 5000,
    imageUrl: img('shiseido-serum'),
    condition: 'Brand New',
    isAuction: false,
    status: 'sold',
    createdAt: '2026-01-10T11:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'd programバイタライジングクリーム 大容量',
    price: 8000,
    imageUrl: img('cream-large'),
    condition: 'Brand New',
    isAuction: false,
    status: 'draft',
    createdAt: '2026-03-05T16:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'D&S マルチピーラー 3way 皮むき器',
    price: 980,
    imageUrl: img('kitchen-peeler'),
    condition: 'Brand New',
    isAuction: false,
    status: 'active',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'dプログラム スキンケアトライアルセット',
    price: 888,
    imageUrl: img('skincare-trial'),
    condition: 'Brand New',
    isAuction: true,
    status: 'sold',
    createdAt: '2026-02-18T13:00:00Z',
  },
]

export const MOCK_AUCTIONS: AdminAuction[] = [
  {
    id: 'auc-1',
    productName: 'D-UP パーフェクトエクステンションマスカラ ブラック',
    imageUrl: img('mascara-black'),
    startingPrice: 300,
    currentBid: 650,
    bidCount: 2,
    endTimeISO: hoursFromNow(18),
    status: 'active',
  },
  {
    id: 'auc-2',
    productName: 'Nintendo Switch OLED ホワイト 本体 新品未使用',
    imageUrl: img('nintendo-switch'),
    startingPrice: 25000,
    currentBid: 38000,
    bidCount: 7,
    endTimeISO: hoursFromNow(22),
    status: 'active',
  },
  {
    id: 'auc-3',
    productName: 'ポケモンカード 151 BOX シュリンク付き',
    imageUrl: img('pokemon-cards'),
    startingPrice: 8000,
    currentBid: 12500,
    bidCount: 3,
    endTimeISO: hoursFromNow(44),
    status: 'active',
  },
  {
    id: 'auc-4',
    productName: '【新品】d プログラム エッセンスイン クレンジング',
    imageUrl: img('cleansing-essence'),
    startingPrice: 1500,
    currentBid: 3300,
    bidCount: 6,
    endTimeISO: new Date(Date.now() - 3600_000).toISOString(),
    status: 'ended',
  },
  {
    id: 'auc-5',
    productName: 'D-UP パーフェクトエクステンションマスカラ ブラウン',
    imageUrl: img('mascara-brown'),
    startingPrice: 200,
    currentBid: 550,
    bidCount: 4,
    endTimeISO: new Date(Date.now() - 7200_000).toISOString(),
    status: 'ended',
  },
  {
    id: 'auc-6',
    productName: 'dプログラム スキンケアトライアルセット',
    imageUrl: img('skincare-trial'),
    startingPrice: 500,
    currentBid: 888,
    bidCount: 3,
    endTimeISO: new Date(Date.now() - 86400_000).toISOString(),
    status: 'ended',
  },
]
